name: Build
# Workflow to Cythonize Python source code
# The workflow is called from the main CI/CD Pipeline

on:
  workflow_call:

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      # Checkout current repository's code
      - name: Fetch repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      # Install Python 3.10.12
      - name: Setup Python 3.10.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.12"

      # Create a directory for the built artifacts
      - name: Create build directory
        run: mkdir -p ${GITHUB_WORKSPACE}/build

      # Download the compiled artifacts from a successful run of this workflow
      - name: Download compiled artifacts
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: main_pipeline.yml
          branch: ${{ github.ref_name }}
          workflow_conclusion: success
          name: compiled-artifacts
          path: ${{ github.workspace }}/build
          if_no_artifact_found: warn
        continue-on-error: true

      # Create a virtual environment for the compiler
      - name: Create compile virtual environment
        run: |
          python3 -m venv ${GITHUB_WORKSPACE}/compiler/venv
          source ${GITHUB_WORKSPACE}/compiler/venv/bin/activate
          python3 -m pip install --upgrade pip
          python3 -m pip install -r ${GITHUB_WORKSPACE}/compiler/requirements.txt

      # Run the compiler
      - name: Run compiler
        run: ${GITHUB_WORKSPACE}/compiler/src/compile.sh --src ${GITHUB_WORKSPACE}/src --dst ${GITHUB_WORKSPACE}/build --branch main

      # Add sh scripts to the build directory
      - name: Add sh scripts
        run: cp ${GITHUB_WORKSPACE}/src/*.sh ${GITHUB_WORKSPACE}/build

      # Upload the compiled artifacts
      - name: Upload compiled artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compiled-artifacts
          path: ${{ github.workspace }}/build

      # Print success message
      - name: Compilation succeeded
        if: success()
        run: echo "✅ Compilation succeeded!"

      # Print error message
      - name: Compilation failed
        if: failure()
        run: echo "❌ Compilation failed!" >&2