name: Docker Image Build

on:
  workflow_call:

jobs:
  docker_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download compiled artifacts
        uses: actions/download-artifact@v4
        with:
          name: compiled-code
          path: ${{ github.workspace }}/build

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ github.workspace }}
          file: ${{ github.workspace }}/Dockerfile
          push: false
          tags: docker_calculator:${{ github.ref_name == 'main' && 'latest' || (github.ref_name == 'dev' && 'dev' || github.ref_name) }}