name: Docker Image Build

on:
  workflow_call:

jobs:
  docker_build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: docker_calculator:${{ github.ref_name == 'main' && 'latest' || (github.ref_name == 'dev' && 'dev' || github.ref_name) }}