name: Docker Image Build

on:
  workflow_call:

jobs:
  docker_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download compiled artifacts into build/
        uses: actions/download-artifact@v4
        with:
          name: compiled-code
          path: ${{ github.workspace }}/build

      - name: List contents of build/ for debug
        run: |
          echo "Contents of build folder:"
          ls -lR ${{ github.workspace }}/build

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ github.workspace }}
          file: ${{ github.workspace }}/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/simple-docker-calculator:${{ github.ref_name == 'main' && 'latest' || 'dev' }}