name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:
  pull_request:

jobs:
  code_clean_check:
    uses: ./.github/workflows/code_check.yml

  test:
    needs: code_clean_check
    uses: ./.github/workflows/test.yml

  build:
    needs: test
    uses: ./.github/workflows/build.yml

  build_container:
    needs: build
    uses: ./.github/workflows/docker_build.yml