name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test.yml

  build:
    needs: test
    uses: ./.github/workflows/build.yml