name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:
  pull_request:

jobs:
  code_clean_check:
    uses: ${{ github.workspace }}/.github/workflows/code_check.yml

  test:
    uses: ${{ github.workspace }}/.github/workflows/test.yml

  build:
    needs: [code_clean_check, test]
    uses: ${{ github.workspace }}/.github/workflows/build.yml

  build_container:
    needs: build
    uses: ${{ github.workspace }}/.github/workflows/docker_build.yml