name: Test
# Workflow to test the Python source code
# The workflow is called from the main CI/CD Pipeline

on:
  workflow_call:

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      # Checkout current repository's code
      - name: Fetch repository
        uses: actions/checkout@v3

      # Install Python 3.10.12
      - name: Setup Python 3.10.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.12"

      # Create a virtual environment for the tests
      - name: Create test virtual environment
        run: |
          python3 -m venv ${GITHUB_WORKSPACE}/test/venv
          source ${GITHUB_WORKSPACE}/test/venv/bin/activate
          python3 -m pip install -r ${GITHUB_WORKSPACE}/test/requirements.txt
          python3 -m pip install -e ${GITHUB_WORKSPACE}

      # Set coverage threshold
      - name: Set coverage threshold based on branch
        id: threshold
        run: |
          BRANCH="${GITHUB_REF##*/}"
          if [ "$BRANCH" = "main" ]; then
            echo "value=90" >> "$GITHUB_OUTPUT"
          else
            echo "value=80" >> "$GITHUB_OUTPUT"
          fi

      # Run tests and generate coverage
      - name: Run tests and generate coverage
        run: |
          coverage run -m pytest
          coverage report --fail-under=${{ steps.threshold.outputs.value }}
          coverage html

      # Upload coverage
      - name: Upload coverage HTML report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/

      # Print success message
      - name: Tests passed
        if: success()
        run: echo "✅ Tests passed!"

      # Print error message
      - name: Tests failed
        if: failure()
        run: echo "❌ Tests failed!" >&2
